### PR TITLE
Replace the icon with @yamada-ui/lucide 

### LINKED ISSUE #36: Replace the icon with `@yamada-ui/lucide`
### Subject

All pages

### Description

Currently, We are using the icon from `components/media-and-icons`, but I would like to replace it with the icon from `@yamada-ui/lucide`.

### Are you willing to participate in the development of this feature and create a pull request?

None

### PR DESCRIPTION
**Pull request by cidkumagai**
Closes #36 

## Description
Replace the icon with @yamada-ui/lucide

### CODE REVIEW

**Review by 108yen — CHANGES_REQUESTED** [review]
Because `@yamada-ui/lucide` is not installed, `pnpm dev` is not working.
Have you checked in your local environment?
You should have to make sure the icons are the right size as you make your replacements.

**Comment by cidkumagai** [comment]
@108yen 
sorry, I might have accidentally deleted a package while resolving the conflict.

**Comment by 108yen** [comment]
@cidkumagai 
There are a lot of places that are out of alignment, so please check.

**Review by 108yen — COMMENTED** [review]
I haven't checked all of them, but don't these differences matter?

https://github.com/yamada-ui/yamada-colors/assets/9676316/d8e895bb-ba8e-46ae-91ea-608409d90c7f

https://github.com/yamada-ui/yamada-colors/assets/9676316/1ff8bebb-4ef3-4bd1-afc8-aa4e2ae8c7f0

https://github.com/yamada-ui/yamada-colors/assets/9676316/2c2db174-f6dc-418a-bc2c-a8404185e8ff

https://github.com/yamada-ui/yamada-colors/assets/9676316/fadb9860-9c91-40a2-899d-bcb150ca9776

https://github.com/yamada-ui/yamada-colors/assets/9676316/3e96c176-538d-4fe7-b3f6-1057f4574bf1

https://github.com/yamada-ui/yamada-colors/assets/9676316/7d8dbefe-4e01-46e0-bb51-2b635bbc303a

**Comment by cidkumagai** [comment]
@108yen 
Could you please let me know what tools you are using in the video?

**Comment by 108yen** [comment]
> @108yen Could you please let me know what tools you are using in the video?

I just switch tabs in Chrome.

**Review by 108yen — DISMISSED** [review]

**Review by kurakke — COMMENTED** [review]
I think the changes are fine, but it would be great if you could resolve the conflicts in package.json and pnpm-lock.yaml and fix the Vercel deployment failure!

**Review by kurakke — APPROVED** [review]

**Review by 108yen — APPROVED** [review]

**Review by 108yen — APPROVED** [review]

**Comment by hirotomoyamada** [comment]
@kurakke 

Please approve!

**Review by kurakke — APPROVED** [review]

**Pull request merged**
